name: Services Tests Passing

on:
  push:
    branches:
      - '**' # all branches
  pull_request:
    branches:
      - '**' # all branches

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Verify go.mod exists
        working-directory: Services
        run: |
          if [ ! -f go.mod ]; then
            echo "go.mod not found in Services/"
            exit 1
          fi

      - name: Install dependencies
        working-directory: Services
        run: go mod tidy

      - name: Run tests
        working-directory: Services
        run: go test -v ./...

  require-tests-passing:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'pull_request'

    steps:
      - name: Check if tests passed
        run: |
          if [ "${{ needs.test.result }}" != "success" ]; then
            echo "Tests did not pass. Merge is not allowed."
            exit 1
          fi